import Web3 from "web3";

export const web3 = new Web3(import.meta.env.VITE_RPC_URL);
export const btcAbi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "toUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "iteration",
        type: "uint8",
      },
    ],
    name: "Debug",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "toUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "fromLevel",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "income",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "incomeToTransfer",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "incomeType",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "btcPrice",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "receiverPackageId",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "fromPackageId",
        type: "uint8",
      },
    ],
    name: "FlushIncome",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "fromUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "toUser",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "level", type: "uint8" },
      {
        indexed: false,
        internalType: "uint8",
        name: "fromPackageId",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "incomeType",
        type: "string",
      },
    ],
    name: "FlushIncomeBackup",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "toUser",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "level", type: "uint8" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountToTransfer",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "fromPackage",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "btcPrice",
        type: "uint256",
      },
    ],
    name: "LevelIncome",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "toUser",
        type: "address",
      },
      { indexed: false, internalType: "uint16", name: "level", type: "uint16" },
      {
        indexed: false,
        internalType: "uint8",
        name: "fromPackageId",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "LevelIncomeBackup",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "toUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "fromLevel",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "receiverPackageId",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "income",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "finalIncome",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "btcPrice",
        type: "uint256",
      },
    ],
    name: "MatrixIncome",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "fromUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "toUser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "income",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "fromPackageId",
        type: "uint8",
      },
    ],
    name: "MatrixIncomeBackup",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "action",
        type: "string",
      },
      {
        indexed: true,
        internalType: "address",
        name: "executor",
        type: "address",
      },
    ],
    name: "OperatorAction",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "payment",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "finalPayment",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "btcPrice",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "paymentInUsd",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "toPackageId",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sponsorAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "UpgradePackage",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "payment",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "toPackageId",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "txHash",
        type: "string",
      },
    ],
    name: "UpgradePackageForBackup",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "maliciousAddress",
        type: "address",
      },
    ],
    name: "UserBlacklisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "string",
        name: "userId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payment",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "paymentInUsd",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "toPackageId",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sponsorAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "spillAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "UserRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "string",
        name: "userId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sponsorAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "spillAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "UserRegisteredBackup",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_BATCH_SIZE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REFERRAL_PERCENT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "aggregator",
    outputs: [
      {
        internalType: "contract AggregatorV3Interface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_maliciousAddress", type: "address" },
    ],
    name: "blacklistAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "blacklistedAddresses",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "btcbToken",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "fromUserId", type: "string" },
          { internalType: "string", name: "toUserId", type: "string" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "time", type: "uint256" },
          { internalType: "uint8", name: "fromPackageId", type: "uint8" },
        ],
        internalType: "struct BTCMINE.MatrixIncomeMigration[]",
        name: "migrations",
        type: "tuple[]",
      },
      { internalType: "string", name: "incomeType", type: "string" },
    ],
    name: "bulkMigrateMatrixIncome",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "fromUserId", type: "string" },
          { internalType: "string", name: "toUserId", type: "string" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "time", type: "uint256" },
          { internalType: "uint8", name: "fromPackageId", type: "uint8" },
        ],
        internalType: "struct BTCMINE.ReferralIncomeMigration[]",
        name: "migrations",
        type: "tuple[]",
      },
      { internalType: "string", name: "incomeType", type: "string" },
    ],
    name: "bulkMigrateReferralIncome",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "fromUserId", type: "string" },
          { internalType: "string", name: "toUserId", type: "string" },
          { internalType: "uint8", name: "level", type: "uint8" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "time", type: "uint256" },
          { internalType: "uint8", name: "fromPackageId", type: "uint8" },
        ],
        internalType: "struct BTCMINE.TeamIncomeMigration[]",
        name: "migrations",
        type: "tuple[]",
      },
      { internalType: "string", name: "incomeType", type: "string" },
    ],
    name: "bulkMigrateTeamIncome",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "user", type: "address" },
          { internalType: "string", name: "sponsorId", type: "string" },
          { internalType: "string", name: "spillId", type: "string" },
          { internalType: "string", name: "userId", type: "string" },
          { internalType: "uint256", name: "activationTime", type: "uint256" },
          { internalType: "uint256", name: "payment", type: "uint256" },
          { internalType: "uint8", name: "packageId", type: "uint8" },
          { internalType: "string", name: "txHash", type: "string" },
        ],
        internalType: "struct BTCMINE.RegistrationInputForBackup[]",
        name: "inputs",
        type: "tuple[]",
      },
    ],
    name: "bulkRegisterAndUpgradePackage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "directRequirements",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "address", name: "_operator", type: "address" },
      { internalType: "address", name: "_btcbToken", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "isUserRegistered",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "levelPercentages",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "operator",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "packages",
    outputs: [
      { internalType: "uint256", name: "usdPrice", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "referralIncome",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sponsor", type: "address" },
      { internalType: "address", name: "spillAddress", type: "address" },
      { internalType: "string", name: "userId", type: "string" },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "string", name: "userId", type: "string" },
    ],
    name: "setUserDetails",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "userId", type: "string" },
          { internalType: "uint256", name: "amountSum", type: "uint256" },
          { internalType: "address", name: "userAddress", type: "address" },
        ],
        internalType: "struct BTCMINE.IncomeInfo[]",
        name: "incomeInfos",
        type: "tuple[]",
      },
      { internalType: "uint8", name: "level", type: "uint8" },
      { internalType: "uint8", name: "status", type: "uint8" },
      { internalType: "uint8", name: "action", type: "uint8" },
    ],
    name: "shortLevelIncomeBackup",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "userId", type: "string" },
          { internalType: "uint256", name: "amountSum", type: "uint256" },
          { internalType: "address", name: "userAddress", type: "address" },
        ],
        internalType: "struct BTCMINE.IncomeInfo[]",
        name: "incomeInfos",
        type: "tuple[]",
      },
      { internalType: "uint8", name: "status", type: "uint8" },
      { internalType: "uint8", name: "action", type: "uint8" },
    ],
    name: "shortMatrixIncomeBackup",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "sponsors",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_newOperator", type: "address" },
    ],
    name: "updateOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "toPackageId", type: "uint8" }],
    name: "upgradePackages",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "userCount",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "userIdToAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint8", name: "", type: "uint8" },
    ],
    name: "userPackages",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "users",
    outputs: [
      { internalType: "uint16", name: "directCount", type: "uint16" },
      { internalType: "address", name: "sponsorAddress", type: "address" },
      { internalType: "string", name: "userId", type: "string" },
      { internalType: "uint256", name: "totalInvested", type: "uint256" },
      { internalType: "uint256", name: "directIncome", type: "uint256" },
      { internalType: "uint256", name: "totalIncome", type: "uint256" },
      { internalType: "uint256", name: "flushIncome", type: "uint256" },
      { internalType: "uint256", name: "matrixIncome", type: "uint256" },
      { internalType: "uint256", name: "levelIncome", type: "uint256" },
      { internalType: "uint8", name: "lastPackage", type: "uint8" },
      { internalType: "address", name: "spillAddress", type: "address" },
      { internalType: "uint8", name: "placements", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tokenAddress", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "withdrawBtcB",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
